// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GLAddition")
                        .HasColumnType("double precision");

                    b.Property<int>("GLAxis")
                        .HasColumnType("integer");

                    b.Property<double>("GLCylinder")
                        .HasColumnType("double precision");

                    b.Property<double>("GLIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("GLNumber")
                        .HasColumnType("double precision");

                    b.Property<double>("GLPrizma")
                        .HasColumnType("double precision");

                    b.Property<string>("GModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GPD")
                        .HasColumnType("integer");

                    b.Property<double>("GRAddition")
                        .HasColumnType("double precision");

                    b.Property<int>("GRAxis")
                        .HasColumnType("integer");

                    b.Property<double>("GRCylinder")
                        .HasColumnType("double precision");

                    b.Property<double>("GRIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("GRNumber")
                        .HasColumnType("double precision");

                    b.Property<double>("GRPrizma")
                        .HasColumnType("double precision");

                    b.Property<int>("LAxis")
                        .HasColumnType("integer");

                    b.Property<double>("LBC")
                        .HasColumnType("double precision");

                    b.Property<double>("LCylinder")
                        .HasColumnType("double precision");

                    b.Property<double>("LNumber")
                        .HasColumnType("double precision");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PreGLAddition")
                        .HasColumnType("double precision");

                    b.Property<int>("PreGLAxis")
                        .HasColumnType("integer");

                    b.Property<double>("PreGLCylinder")
                        .HasColumnType("double precision");

                    b.Property<double>("PreGLIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("PreGLNumber")
                        .HasColumnType("double precision");

                    b.Property<double>("PreGLPrizma")
                        .HasColumnType("double precision");

                    b.Property<int>("PreGPD")
                        .HasColumnType("integer");

                    b.Property<double>("PreGRAddition")
                        .HasColumnType("double precision");

                    b.Property<int>("PreGRAxis")
                        .HasColumnType("integer");

                    b.Property<double>("PreGRCylinder")
                        .HasColumnType("double precision");

                    b.Property<double>("PreGRIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("PreGRNumber")
                        .HasColumnType("double precision");

                    b.Property<double>("PreGRPrizma")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RAxis")
                        .HasColumnType("integer");

                    b.Property<double>("RBC")
                        .HasColumnType("double precision");

                    b.Property<double>("RCylinder")
                        .HasColumnType("double precision");

                    b.Property<double>("RNumber")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
